run:
  timeout: 3m
  tests: true

linters:
  enable:
    - goimports      # Форматирование + автоматическая сортировка импортов
    - govet          # Официальные проверки компилятора (nil, формат, гонки)
    - staticcheck    # Баги, устаревший API, неэффективный код
    - errcheck       # Игнорирование ошибок (самая частая причина падений)
    - unused         # Мёртвый код, неиспользуемые функции/переменные

linters-settings:
  goimports:
    local-prefixes: github.com/kgugunava/link-service

issues:
  exclude-use-default: false